#!/usr/bin/env python3

import sys

def help(exitcode=0):
    helpstr = """USAGE:
    """
    print(helpstr)
    sys.exit(exitcode)

def main(args):
    for i, arg in enumerate(args):
        print(i, arg)
    help()
    
main(sys.argv)
