#!/bin/sh

CONFIG_DIR="$HOME/.config/yabai"

source "$CONFIG_DIR/window_rules.sh"
source "$CONFIG_DIR/signals.sh"
source "$CONFIG_DIR/workspaces.sh"

# load the scripting addon
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#sudo yabai --load-sa

# set the default layout
yabai -m config layout bsp

# custom bar padding
yabai -m config external_bar all:26:0 

# set gaps
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# split windows 50/50
yabai -m config split_ratio 0.5

# make focus follow the mouse
yabai -m config focus_follows_mouse autoraise

# make mouse follow focus
yabai -m config mouse_follows_focus on

# only shadows for floating windows
yabai -m config window_shadow float
