#!/usr/bin/env sh

ROFI="rofi -dmenu -theme $XDG_CONFIG_HOME/rofi/list.rasi -p emoji"

chosen=$(grep -v "#" $XDG_DATA_HOME/emoji | cut -d';' -f1 | $ROFI -select "$@" )

[ "$chosen" != "" ] || exit

emoji=$(echo "$chosen" | sed "s/ .*//")

echo "$emoji" | tr -d '\n' | xclip -selection clipboard
echo "$emoji" | tr -d '\n' | xclip
notify-send "'$emoji' copied to clipboard."
