#!/usr/bin/env sh

DOTFILES="$HOME/documents/dotfiles"
MANIFEST="$DOTFILES/MANIFEST"
INSTALL_PATH=".local/bin/scripts"
SCRIPTS_ROOT="$DOTFILES/$INSTALL_PATH"

ROFI="rofi -dmenu -theme $XDG_CONFIG_HOME/rofi/list.rasi -i -p"

function pick_filename {
	existing=$( ls "$SCRIPTS_ROOT" | grep "\.png\$" )
	filename=$( echo -e "$existing" | $ROFI "filename" )
	while [ -f "$SCRIPTS_ROOT/$filename" -o -z $filename ]; do
		filename=$( echo -e "$existing" | $ROFI "invalid filename" )
	done
	echo "$filename"
}

# pick a filename, create a blank script, open it
function generate_script {
  # create the script
  filename="$( pick_filename )"
  script_path="$SCRIPTS_ROOT/$filename"
  touch "$script_path"
  # check if the file was created
  if [ -f "$script_path" ]; then
    chmod u+x "$script_path"
    echo -e "#!/usr/bin/env sh\n\necho \"hello world\"" > "$script_path"
    # link the script in the MANIFEST
    sed -i "s,\\(# scripts\\),&\\n$INSTALL_PATH/$filename\\t$INSTALL_PATH/$filename," "$MANIFEST"
    # install the script
    $DOTFILES/install 
    # start editing the script
    xdg-open "$HOME/$INSTALL_PATH/$filename"
  fi
}

function menu {
  selection=$( echo -e "Script" | $ROFI music ) 
  case "$selection" in
    "Script") generate_script ;;
  esac
}

menu
