#!/usr/bin/env sh

function load {

	default_sink=$( pactl info | sed -En 's/Default Sink: (.*)/\1/p' )

	# Create a sink where we will mix the microphone and some application audio.
	# This is the sink our audience will listen to
	pactl load-module module-null-sink sink_name=audience_sink \
	sink_properties=device.description=audience_mix \
	> /tmp/loopback_modules

	# Create a sink which takes application audio and sends it to our speakers and the special mixing sink we just created
	# This is our private sink
	pactl load-module module-combine-sink sink_name=application_sink \
	slaves=audience_sink,bluez_output.00_1B_66_E9_BA_22.a2dp-sink \
	sink_properties=device.description=application_mix \
	>> /tmp/loopback_modules
	
	# Loopback our actual microphone to our mixing (audience) sink (pactl list sources short)
	pactl load-module module-loopback source=alsa_input.pci-0000_00_1f.3.analog-stereo \
	sink=audience_sink latency_msec=20 source_dont_move=true sink_dont_move=true \
	>> /tmp/loopback_modules
	
}

function unload {
	for module in $( cat /tmp/loopback_modules | xargs ); do
		pactl unload-module $module
	done
}

case "$1" in
	"load") load ;;
	"unload") unload ;;
	*)
		unload
		load
		;;
esac
