#!/usr/bin/env sh

# todo fix urxvt bg

# recache the colors
wal -i "$(< "$XDG_CACHE_HOME/wal/wal")" -n --backend colorz > /dev/null 2>&1

# load the xresources
xrdb "$XDG_CONFIG_HOME/X11/xresources"

# reload bashrc
source "$HOME/.bashrc"

# discord 
pywal-discord

# firefox
python3 -m pywalfox update > /dev/null

# steam
# wal_steam > /dev/null

# restart xob
start-xob > /dev/null

# rebuild slock
pushd $HOME/aur/slock > /dev/null
  sudo make clean install > /dev/null
popd > /dev/null

# restart eww
pkill -f start-eww
start-eww &

# restart dunst
killall dunst 2> /dev/null
dunst &

# scan for wifi
kill $( ps -aux | grep "wifi --scan" | grep -v grep | awk '{ print $2 }' | xargs ) 2> /dev/null
kill $( ps -aux | grep "sleep 60" | grep -v grep | awk '{ print $2 }' | xargs ) 2> /dev/null
wifi --scan > /dev/null & 
# update the weather
kill $( ps -aux | grep "weather --update" | grep -v grep | awk '{ print $2 }' | xargs ) 2> /dev/null
kill $( ps -aux | grep "sleep 3600" | grep -v grep | awk '{ print $2 }' | xargs ) 2> /dev/null
weather --update > /dev/null &

# restart eww
killall eww 2> /dev/null
eww daemon > /dev/null 2>&1
