#!/usr/bin/env sh

function open {
  eww open "sidebar"
  eww open "time"
  eww open "date"
  eww open "weather"
  eww open "wireless"
  eww open "stats"
  eww open "mpd"
}

function close {
  eww close-all
}

# sets WIDTH and HEIGHT
eval $(xdotool getdisplaygeometry --shell)

echo hello
 
while :; do
  # sets X and Y
  eval $(xdotool getmouselocation --shell)

	echo $X $Y "$(( $HEIGHT / 2))"
 
  # bottom left
	if [[ "$X" -lt "2" && "$Y" -gt "$(( $HEIGHT / 2))" && $( pgrep -c minecraft ) -lt 1 ]]; then
   echo open 
	 open > /dev/null
	fi
    
	[[ "$X" -gt "$(( $WIDTH / 3 ))" && "$( eww state )" ]] \
    && close > /dev/null

  sleep 0.1
done
