#!/usr/bin/env sh
EWW_CONFIG="$XDG_CONFIG_HOME/eww/eww.yuck"

function open {
  eww open "sidebar"
  eww open "time"
  eww open "date"
  eww open "weather"
  eww open "wireless"
  eww open "stats"
  eww open "mpd"
}

function close {
  eww close-all
}

# sets WIDTH and HEIGHT
eval $(xdotool getdisplaygeometry --shell)

# set the display in the config
connected_displays=$( xrandr | grep -Eo '[0-9]{2}\.[0-9]{2}\*\+' | wc -l )
display=$(( connected_displays - 1 ))
sed -i "s/:monitor [0-9]/:monitor $display/g" "$EWW_CONFIG"

while :; do
  # sets X and Y
  eval $(xdotool getmouselocation --shell)

  # bottom left
	if [[ "$X" -lt "2" && "$Y" -gt "$(( $HEIGHT / 2))" && $( pgrep -c minecraft ) -lt 1 ]]; then
	 open > /dev/null
	fi
    
	[[ "$X" -gt "$(( $WIDTH / 3 ))" && "$( eww state )" ]] \
    && close > /dev/null

  sleep 0.1
done
