#!/bin/bash

ROFI="rofi -dmenu -theme $XDG_CONFIG_HOME/rofi/list.rasi -p"

WEBCAMS=$( ls /dev/video* )


function start_stream {
  SRC="v4l2src device=$1"
  FORMATTER="video/x-raw,width=640,height=480,framerate=30/1"
  CONVERTER="videoconvert"
  ENCODER="jpegenc"
  PAYLOADER="rtpjpegpay"
  NETWORK_SINK="udpsink host=127.0.0.1 port=1234"
  MULTI_SINK="multiudpsink clients=127.0.0.1:5000,127.0.0.1:5004,192.168.2.15:2000"
  gst-launch-1.0 -v $SRC ! $FORMATTER ! $CONVERTER ! $ENCODER ! $PAYLOADER ! $NETWORK_SINK &
}

function watch_stream {
  SRC="udpsrc port=1234"
  FORMATTER="application/x-rtp,encoding-name=JPEG,payload=26"
  DEPAYLOADER="rtpjpegdepay"
  DECODER="jpegdec"
  SINK="autovideosink"
  gst-launch-1.0 -v $SRC ! $FORMATTER ! $DEPAYLOADER ! $DECODER ! $SINK &
}

function watch_local {
  SRC="v4l2src device=$1"
  FORMATTER="video/x-raw,width=640,height=480,framerate=30/1"
  ENCODER="jpegenc"
  DECODER="jpegdec"
  SINK="autovideosink"
  gst-launch-1.0 --gst-fatal-warnings -v $SRC ! $FORMATTER ! $ENCODER ! $DECODER ! $SINK &
}

function menu {
	selection=$( echo -e "$WEBCAMS" | $ROFI "webcam" )
	case "$selection" in 
		*"video"*) watch_local "$selection" > /dev/null 2&>1 
	esac
}

menu

#start_stream 
#watch_stream 
#watch_local > /dev/null
