#!/usr/bin/perl

use strict;
use warnings;

my $font1 = "monospace";
my $font2 = "JoyPixels";
my $font3 = "Noto Color Emoji";
my $base_size = 14;

my $size = $base_size;

sub on_user_command
{
	my ($self, $cmd) = @_;

	if ($cmd eq "zoom:in") {
		$size++;
	} elsif ($cmd eq "zoom:out") {
		$size-- if $size gt 1;
	} elsif ($cmd eq "zoom:eq") {
		$size = $base_size;
	}

	# my $size = $level * $base_size;
	$self->cmd_parse("\033]50;xft:${font1}:size=${size},xft:${font2}:size=${size},xft:${font3}:size=${size}\007");
}
