#!/bin/sh

function toggle {
	if [ "$currOutput" == "" ]
	then
    	echo " "$wifi > ~/.config/polybar/scripts/curr-wifi
	else
    	if [ "$wifi" == "" ]
    	then
        	echo "" > ~/.config/polybar/scripts/curr-wifi
    	else
        	echo "" > ~/.config/polybar/scripts/curr-wifi
    	fi
	fi
}

function update {
	if [ "$wifi" == "" ]
	then 
		echo "" > ~/.config/polybar/scripts/curr-wifi
	else
		if [ "$currOutput" == "" ]
		then
			echo "" > ~/.config/polybar/scripts/curr-wifi
		fi
	fi
}

currOutput=$(cat ~/.config/polybar/scripts/curr-wifi)
wifi=$(nmcli -f in-use,ssid dev wifi | grep '*' | tr -s ' ' | cut -d' ' -f 2 )

cat ~/.config/polybar/scripts/curr-wifi 
update

case $1 in 
	"-t")
		toggle
		;;
esac


